seed: 1
model: 'tcspace'
exp_name: pong
resume: false
load_time_consistency: true
add_flow: true
save_relevant_objects: false
resume_ckpt: ''
#'../old_models/actually_new_model_000005041.pth'
# ''
# ../old_models/model_000005001.pth
#resume_ckpt: '../output/checkpoints/tmp/model_pretrained.pth'
# '../output/checkpoints/mid/mspacman_pt_seed0_aow0.0/model_000160101.pth'
# '../output/checkpoints/mspacman_atari_pretrained/model.pth'
#
# '../output/checkpoints/mspacman_atari+z_what_1e-2/model_000162501.pth'
#'../output/checkpoints/mspacman_atari+z_area_object_1e1/model_000186501.pth'
# '../output/checkpoints/mspacman_baseline/model_000177001.pth'
# 'result_checkpoints/base_z_what_model_000078001.pth'
# 'output/checkpoints/atari_mspacman/model_000079001.pth'
# '../pretrained/atari_joint.pth'
parallel: true
device_ids: [0,1,2,3]
device: 'cuda:0'

logdir: '../output/logs/final'
checkpointdir: '../output/checkpoints/final'
evaldir: '../output/eval'

dataset: 'ATARI'
dataset_style: ''
dataset_roots:
  OBJ3D_SMALL: '../data/OBJ3D_SMALL'
  OBJ3D_LARGE: '../data/OBJ3D_LARGE'
  ATARI: '../aiml_atari_data'

train:
  log: true
  batch_size: 16
  max_epochs: 10000
  max_steps: 5000
  print_every: 200
  save_every: 100
  num_workers: 8
  clip_norm: 1.0
  max_ckpt: 4
  eval_on: false
  eval_every: 10
  solver:
    fg:
      optim: 'RMSprop'
      lr: 3e-5
    bg:
      optim: 'Adam'
      lr: 1e-3

arch:
  motion_input: false
  motion: true
  motion_kind: 'mode'
  G: 16

  fix_alpha_steps: -1
  fix_alpha_value: 0.1

  motion_underestimating: 1.5

# For engine.eval
eval:
  checkpoint: 'last'
  metric: ap_avg

gamelist: [
    'Pong-v0',
    ]
